# Generated by Django 4.2.10 on 2024-03-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
