# Generated by Django 4.1.3 on 2022-11-23 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desciption', models.CharField(max_length=200)),
                ('required_stationary', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('canvas_size', models.CharField(blank=True, max_length=8)),
                ('image', models.ImageField(upload_to='artwork/')),
                ('uploaded', models.DateField(auto_now_add=True)),
                ('art_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artpage.arttype')),
            ],
        ),
    ]
