# Generated by Django 4.1.3 on 2022-11-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpage', '0002_collection_artpiece_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
