# Generated by Django 4.1.3 on 2022-11-29 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artpage', '0004_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='artpage.creator'),
        ),
    ]
