# Generated by Django 4.1.3 on 2024-02-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpage', '0006_artpiece_landscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_collection',
            field=models.BooleanField(default=True),
        ),
    ]
