# Generated by Django 4.2.10 on 2024-02-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpage', '0007_collection_is_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpiece',
            name='landscape',
        ),
        migrations.AddField(
            model_name='artpiece',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/'),
        ),
    ]
