# Generated by Django 4.2.10 on 2024-02-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpage', '0009_artpiece_product_sticker_print_photographyprints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='total_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merch',
            name='total_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photographyprints',
            name='total_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='total_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='total_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
