# Generated by Django 4.2.10 on 2024-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpage', '0010_artpiece_total_stock_merch_total_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merch',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photographyprints',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
