# Generated by Django 4.2.10 on 2024-02-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpage', '0011_artpiece_long_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='extra_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='artpiece',
            name='second_image',
        ),
        migrations.AddField(
            model_name='artpiece',
            name='extra_images',
            field=models.ManyToManyField(blank=True, to='artpage.extraimages'),
        ),
        migrations.AddField(
            model_name='merch',
            name='extra_images',
            field=models.ManyToManyField(blank=True, to='artpage.extraimages'),
        ),
        migrations.AddField(
            model_name='photographyprints',
            name='extra_images',
            field=models.ManyToManyField(blank=True, to='artpage.extraimages'),
        ),
        migrations.AddField(
            model_name='print',
            name='extra_images',
            field=models.ManyToManyField(blank=True, to='artpage.extraimages'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='extra_images',
            field=models.ManyToManyField(blank=True, to='artpage.extraimages'),
        ),
    ]
