# Generated by Django 4.2.10 on 2024-02-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpage', '0012_extraimages_remove_artpiece_second_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='long_description',
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='long_description',
            field=models.TextField(blank=True, max_length=670, null=True),
        ),
        migrations.AlterField(
            model_name='merch',
            name='long_description',
            field=models.TextField(blank=True, max_length=670, null=True),
        ),
        migrations.AlterField(
            model_name='photographyprints',
            name='long_description',
            field=models.TextField(blank=True, max_length=670, null=True),
        ),
        migrations.AlterField(
            model_name='print',
            name='long_description',
            field=models.TextField(blank=True, max_length=670, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='long_description',
            field=models.TextField(blank=True, max_length=670, null=True),
        ),
    ]
