# Generated by Django 4.2.10 on 2024-02-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artpage', '0013_remove_collection_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='long_description',
            field=models.TextField(blank=True, max_length=670, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
