# Generated by Django 4.1.3 on 2022-12-06 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artpage', '0005_artpiece_creator'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='artpage.artpiece'),
        ),
    ]
