# Generated by Django 4.2.10 on 2024-02-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
    ]
