# Generated by Django 4.2.10 on 2024-02-20 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_order_id_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_paid',
        ),
    ]
