# Generated by Django 4.2.10 on 2024-03-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('stripe_shipping_id', models.CharField(max_length=100)),
                ('shipping_description', models.CharField(max_length=300, null=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
