# Generated by Django 4.1.3 on 2022-11-23 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Katelyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('art_style', models.TextField(validators=[django.core.validators.MinLengthValidator(100, 'Must be at least one hundred characters.')])),
                ('creative_universe_exp', models.TextField(validators=[django.core.validators.MinLengthValidator(100, 'Must be at least one hundred characters.')])),
                ('life', models.TextField(validators=[django.core.validators.MinLengthValidator(100, 'Must be at least one hundred characters.')])),
                ('selfie', models.ImageField(blank=True, upload_to='about/')),
                ('favorite_art', models.ImageField(blank=True, upload_to='about/')),
                ('favorite_art_reason', models.ImageField(blank=True, upload_to='about/')),
            ],
        ),
    ]
