# Generated by Django 4.1.3 on 2022-12-06 21:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artpage', '0005_artpiece_creator'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katelyn',
            name='favorite_art',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='life',
        ),
        migrations.AddField(
            model_name='katelyn',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='katelyn',
            name='biography_1',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100, 'Must be at least one hundred characters.')]),
        ),
        migrations.AddField(
            model_name='katelyn',
            name='biography_2',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100, 'Must be at least one hundred characters.')]),
        ),
        migrations.AddField(
            model_name='katelyn',
            name='biography_3',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100, 'Must be at least one hundred characters.')]),
        ),
        migrations.AddField(
            model_name='katelyn',
            name='biography_4',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100, 'Must be at least one hundred characters.')]),
        ),
        migrations.AddField(
            model_name='katelyn',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='katelyn',
            name='favorite_art_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artpage.artpiece'),
        ),
        migrations.AddField(
            model_name='katelyn',
            name='life_info',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100, 'Must be at least one hundred characters.')]),
        ),
        migrations.AddField(
            model_name='katelyn',
            name='places_lived',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(20, 'Must be at least one twenty characters.')]),
        ),
        migrations.AlterField(
            model_name='katelyn',
            name='creative_universe_exp',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100, 'Must be at least one hundred characters.')]),
        ),
        migrations.AlterField(
            model_name='katelyn',
            name='favorite_art_reason',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(50, 'Must be at least one fifty characters.')]),
        ),
    ]
