# Generated by Django 4.1.3 on 2024-01-27 23:52

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_katelyn_favorite_art_remove_katelyn_life_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katelyn',
            name='age',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='art_style',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='biography_1',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='biography_2',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='biography_3',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='biography_4',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='creative_universe_exp',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='favorite_art_piece',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='favorite_art_reason',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='life_info',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='places_lived',
        ),
        migrations.RemoveField(
            model_name='katelyn',
            name='selfie',
        ),
        migrations.AddField(
            model_name='katelyn',
            name='info',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Enter everything you want to say here. You can use markdown to format your text: https://www.markdownguide.org/basic-syntax/', null=True),
        ),
    ]
